---
# ansible-playbook -i "localhost," -c local playbook.yml
# ansible-playbook -i "localhost," -c local playbook.yml --extra-vars="bossjones__passwordstore__user=$(whoami)"
# ansible-playbook --ask-become-pass --check -i "localhost," -c local playbook.yml --extra-vars="bossjones__passwordstore__user=$(whoami)"
# - hosts: localhost
#   connection: local
#   become: true
#   roles:
#     - ../ansible-role-passwordstore

# SOURCE: Inspiration - https://github.com/jan-warchol/ansible-workstation-setup/blob/a7bc1045882a4ab1cc35530083cd10db74c901dd/cli-setup-secrets.yml
# SOURCE: https://www.bootc.net/archives/2013/06/09/my-perfect-gnupg-ssh-agent-setup/

- name: get information about ansible control machine
  hosts: localhost
  connection: local
  become: true
  gather_facts: yes

- name: Setup | gpg key generate and configure
  become: true
  hosts: localhost
  connection: local

  vars:
    pass_gpg_key_fingerprint: "EC5E 11DD EF42 BF79 FBFA 4F4E FF6A DDEB B33A 5D2F"
    key_filename: "GPG_key_{{ pass_gpg_key_fingerprint | replace(' ', '') }}.asc"
    control_machine_ip: "{{ hostvars['localhost'].ansible_default_ipv4.address }}"
    hide_sensitive_logs: false

  # pre_tasks:
  #   # SOURCE: https://superuser.com/questions/624343/keep-gnupg-credentials-cached-for-entire-user-session
  #   # SOURCE: https://superuser.com/questions/1172804/how-to-prevent-gpg-agent-from-timing-out-during-passphrase-collection?rq=1
  #   - name: 'gpg-agent.conf'
  #     copy:
  #       dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
  #       content: |
  #############################################################
  # SOURCE: https://benincosa.com/?p=3235
  #############################################################
  #         default-cache-ttl 600
  #         pinentry-program /usr/local/bin/pinentry
  #         no-grab
  #         max-cache-ttl 172800
  ##############################################################
  #         default-cache-ttl 34560000
  #         max-cache-ttl 34560000
  #         pinentry-timeout 0
  #         pinentry-program /usr/bin/pinentry-curses --timeout 0
  #       mode: 0600
  #     no_log: "{{ hide_sensitive_logs }}"
  # SOURCE: https://benincosa.com/?p=3235
  # SOURCE: https://jimsaunders.net/2017/02/18/setting-up-the-pass-password-manager.html
  roles:
    - role: ../ansible-gpgkey_generate
      gpg_generator_user: "{{ bossjones__passwordstore__user }}"
      gpg_user: "{{ bossjones__passwordstore__user }}"
      gpg_realname: "GPG {{ bossjones__passwordstore__user }} user"
      gpg_useremail: "{{ bossjones__passwordstore__user }}@localhost"
      gpg_pubkeyfile: "{{ bossjones__passwordstore__user }}.pub"
      gpg_privkeyfile: "{{ bossjones__passwordstore__user }}.priv"
      gpg_pubkeyfileexport: "{{ bossjones__passwordstore__user }}.asc"
      gpg_fingerprint: "{{ bossjones__passwordstore__user }}-fingerprint"
      gpg_keylength: 4096
      gpg_subkeylength: 4096
      gpg_expire: 0
      gpg_passphrase: "{{ lookup('env','MY_GPG_PASSPHRASE') }}"
      ## recover files on orchestrator?
      gpg_pull: false

  post_tasks:

    - name: Generate secret key fingerprint file
      shell: |
        gpg2 --fingerprint {{ bossjones__passwordstore__user }}@localhost | grep -v SCEA | head -1 | awk '{print $9$10}' | tee /home/{{ bossjones__passwordstore__user }}/{{ {{ bossjones__passwordstore__user }}-fingerprint }}
      args:
        chdir: "~"
        executable: /bin/bash
      changed_when: false
      register: gpg_user_fingerprint
      become: yes
      become_user: "{{ gpg_generator_user }}"


- name: setup password store
  # hosts: all
  hosts: localhost
  connection: local

  vars:
    pass_gpg_key_fingerprint: "EC5E 11DD EF42 BF79 FBFA 4F4E FF6A DDEB B33A 5D2F"
    key_filename: "GPG_key_{{ pass_gpg_key_fingerprint | replace(' ', '') }}.asc"
    control_machine_ip: "{{ hostvars['localhost'].ansible_default_ipv4.address }}"
    hide_sensitive_logs: false

  # pre_tasks:
  #   # SOURCE: https://superuser.com/questions/624343/keep-gnupg-credentials-cached-for-entire-user-session
  #   # SOURCE: https://superuser.com/questions/1172804/how-to-prevent-gpg-agent-from-timing-out-during-passphrase-collection?rq=1
  #   - name: 'gpg-agent.conf'
  #     copy:
  #       dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
  #       content: |
  #############################################################
  # SOURCE: https://benincosa.com/?p=3235
  #############################################################
  #         default-cache-ttl 600
  #         pinentry-program /usr/local/bin/pinentry
  #         no-grab
  #         max-cache-ttl 172800
  ##############################################################
  #         default-cache-ttl 34560000
  #         max-cache-ttl 34560000
  #         pinentry-timeout 0
  #         pinentry-program /usr/bin/pinentry-curses --timeout 0
  #       mode: 0600
  #     no_log: "{{ hide_sensitive_logs }}"
  # SOURCE: https://benincosa.com/?p=3235
  # SOURCE: https://jimsaunders.net/2017/02/18/setting-up-the-pass-password-manager.html
  roles:
    - ../ansible-role-knownhosts
    - ../ansible-role-passwordstore


  # NOTE: don't forget to cat /etc/X11/Xsession.d/90gpg-agent
