# -*- coding: utf-8 -*-
# tasks for  ansible-role-passwordstore
---
- name: install apt packages
  package:
    name:
      - expect  # for automatic ssh key unlocking
      - gnupg2  # I want to be able to use gpg2 command for compatibility
      - git
      - xclip  # for putting password in clipboard
      - pinentry-tty  # for unlocking keys in agent without gui
      - pwgen  # password generator
  become: yes

- name: ensure directories exist
  file:
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    # - .ssh/keys
    - .gnupg

# - name: copy GPG key for password store
#   copy:
#     dest: "{{ ansible_env.HOME }}/.gnupg/{{ key_filename }}"
#     content: "{{ lookup('passwordstore', 'personal-gpg-key returnall=true') }}"
#     mode: 0600
#   no_log: "{{ hide_sensitive_logs }}"
#   register: gpg_key_status

# - name: import gpg key
#   command: gpg2 --batch --import {{ ansible_env.HOME }}/.gnupg/{{ key_filename }}
#   when: gpg_key_status.changed

# - name: copy GPG trust database so that keys are trusted
#   copy:
#     # note that in src we want the HOME of ansible controller user
#     src: "{{ lookup('env', 'HOME') }}/.gnupg/trustdb.gpg"
#     dest: "{{ ansible_env.HOME }}/.gnupg/trustdb.gpg"
#     mode: 0600

# - name: configure git user email
#   git_config:
#     name: user.email
#     value: "{{ bossjones__passwordstore__git_config_email }}"
#     path: "{{ passwordstore_path }}"

