# -*- coding: utf-8 -*-
# tasks for  ansible-role-passwordstore
---
- name: Install/Setup passwordstore
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - passwordstore
    - xclip
  when: ansible_os_family == "Debian"

- name: Clone passwordstore config
  git:
    repo: https://github.com/gpakosz/.passwordstore
    dest: "{{item.dir}}/.passwordstore"
    version: "master"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__passwordstore__path_to_passwordstore_config}}"

- name: Clone powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{item.dir}}/fonts"
    version: "master"
    depth: 1
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__passwordstore__path_to_passwordstore_config}}"

- name: bootstrap passwordstore.conf
  shell: |
            ln -s -f .passwordstore/.passwordstore.conf
            cp .passwordstore/.passwordstore.conf.local .
            chdir="{{item.dir}}"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__passwordstore__path_to_passwordstore_config}}"

- name: Install powerline fonts
  shell: |
            # install
            cd fonts
            ./install.sh
            # clean-up a bit
            cd ..
            rm -rf fonts
            chdir="{{item.dir}}"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__passwordstore__path_to_passwordstore_config}}"


